### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by JuZiSYJ** [HuiZeng/Image-Adaptive-3DLUT#1]
**torch.utils.ffi** is is deprecated. Please use cpp extensions instead
torch 1.x can not build successfully, could you provide a modefied version using **torch.utils.cpp_extension** ?

**Comment by HuiZeng** [comment]
Hi， currently we only support .c extension. 
cpp_extension may be supported in the future.

**Comment by HuiZeng** [comment]
> **torch.utils.ffi** is is deprecated. Please use cpp extensions instead
> torch 1.x can not build successfully, could you provide a modefied version using **torch.utils.cpp_extension** ?

Hi, we will supported .cpp_extension in a few days.

**Comment by hermosayhl** [comment]
pytorch==0.4.0 is absolutely OK!

**Comment by HuiZeng** [comment]
> **torch.utils.ffi** is is deprecated. Please use cpp extensions instead
> torch 1.x can not build successfully, could you provide a modefied version using **torch.utils.cpp_extension** ?

I have uploaded trilinear_cpp to support torch 1.x. Please import the corresponding version in the python codes.

**Comment by DavidQiuChao** [comment]
> > **torch.utils.ffi** is is deprecated. Please use cpp extensions instead
> > torch 1.x can not build successfully, could you provide a modefied version using **torch.utils.cpp_extension** ?
> 
> I have uploaded trilinear_cpp to support torch 1.x. Please import the corresponding version in the python codes.

Hi, can you explain places needed to modify for detail.

**Comment by HuiZeng** [comment]
I have uploaded a models_x. py to support pytorch 1.x. Please read the updated readme for details.

**Comment by DavidQiuChao** [comment]
> I have uploaded a models_x. py to support pytorch 1.x. Please read the updated readme for details.

many thanks
