### ISSUE TITLE
Unpaired Pretrained Model

### ISSUE THREAD

**Issue by zhenhuahu** [HuiZeng/Image-Adaptive-3DLUT#10]
Hi, thanks for the great work! Can you please share the unpaired pretrained models? Thanks!

**Comment by HuiZeng** [comment]
Hi, sorry for the late reply.
I have uploaded the unpaired pretrained models.
Please note that these models were retrained using the released code. Their quantitative indexes are slightly better than the ones used in the paper.

**Comment by zhenhuahu** [comment]
> Hi, sorry for the late reply.
> I have uploaded the unpaired pretrained models.
> Please note that these models were retrained using the released code. Their quantitative indexes are slightly better than the ones used in the paper.

Thank you so much!
