### ISSUE TITLE
color mismatch

### ISSUE THREAD

**Issue by sdlpkxd** [HuiZeng/Image-Adaptive-3DLUT#11]
Thanks for your great work. 

My pytorch version is 1.6.0, I build the project by ‘cd trilinear_cpp, sh setup.sh’, and then I run 'python demo_eval.py' command and get the enhanced image of a1629.jpg. But I find the 'red' flowers becomes 'blue' flowers, and the ‘blue’ tail of the bird becomes ‘brown’ tail, it's different from the result provided in your paper. Is there something wrong in the model you provided here or is there something else I should do before I run 'python demo_eval.py' ? The following picture is the result I get.

 Look forward your reply.

![result](https://user-images.githubusercontent.com/24651764/95412447-92881d80-095b-11eb-9ad1-423fe153159c.jpg)

**Comment by zhenhuahu** [comment]
Try change line 67 to be

LUT = pred[2] * LUT0.LUT + pred[1] * LUT1.LUT + pred[0] * LUT2.LUT

**Comment by HuiZeng** [comment]
Thanks for pointing out this issue.
As mentioned by @zhenhuahu, there is a bug in reading 8-bit sRGB input. I have fixed it. You can try the updated demo code.

**Comment by sdlpkxd** [comment]
It works, thanks.
