### ISSUE TITLE
Bug in demo_eval.py

### ISSUE THREAD

**Issue by zhenhuahu** [HuiZeng/Image-Adaptive-3DLUT#12]
Hi, thanks again for the great work! I just found a bug in file _demo_eval.py_. OpenCV reads image into BGR, so after line 77, i think image should be converted to RGB before proceeding. 
Please let me know if i'm right.

Thanks again for the great work!

**Comment by HuiZeng** [comment]
Thanks very much for pointing out this bug. I have fixed it to be consistent with the training setting.

**Comment by zhenhuahu** [comment]
> Thanks very much for pointing out this bug. I have fixed it to be consistent with the training setting.

Glad to hear that I can help. Thank you very much for the great work!
