### ISSUE TITLE
about training data

### ISSUE THREAD

**Issue by BoyuanJiang** [HuiZeng/Image-Adaptive-3DLUT#13]
Hi, I want to train the model. I have downloaded dataset from the link you provided, but I am not sure where is train_label.txt and train_input.txt, which is used in datasets.py. Can you provide an example of these two files?

**Comment by HuiZeng** [comment]
Hi, the train_label.txt was provided in the directory: data/fiveK/
![image](https://user-images.githubusercontent.com/12780780/95584461-5beff700-0a70-11eb-8626-b1eb8a29a4cd.png)

**Comment by HuiZeng** [comment]
Please make sure that the input dataset directory in the training code is correct on your device.

**Comment by BoyuanJiang** [comment]
I found it, thank you.
