### ISSUE TITLE
Can you please upload the names of HDR+ dataset?

### ISSUE THREAD

**Issue by zhenhuahu** [HuiZeng/Image-Adaptive-3DLUT#16]
Hi, thanks again for the great work! I was trying to mimic the result of imaging pipeline enhancement. I checked the HDR+ dataset but I can't find the aligned Nexus 6p subset you mentioned in the paper. Can you please give me a hint on the names of HDR+ Dataset? 

Thanks.

**Comment by HuiZeng** [comment]
Hi, the camera device information can be found in the metadata. The name of the subset images were renamed. So I have uploaded the processed HDR+ subset in the same directory with FiveK. You can directly download it.

**Comment by zhenhuahu** [comment]
Thank you so much! As far as I understand, the images in 'middle_480p' is the images in XYZ color space. Do you also generate these XYZ images using LightRoom? I'm quite new to LC. I tried but I wasn't be able to export one image into XYZ color space. All I get is sRGB, display P3, Adobe RGB, photoshop RGB. Can you please give me a hint on how to do this? Thanks.

**Comment by HuiZeng** [comment]
Hi, the HDR+ dataset was processed using Rawpy, which can directly convert to XYZ color space.
For FiveK dataset, I first export to 16-bit ProPhoto RGB, then convert to XYZ color space.
The color transformation information can be found here: http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html

**Comment by HuiZeng** [comment]
Bellow is the matlab code I used to convert from ProPhoto RGB to XYZ:


Pro2XYZ = [0.7976749,  0.1351917,  0.0313534;
           0.2880402,  0.7118741,  0.0000857;
           0.0000000,  0.0000000,  0.8252100];
D50_D65 = [0.9593730,  0.0000000,  0.0000000;
           0.0000000,  1.0000000,  0.0000000;
           0.0000000,  0.0000000,  1.2776246];
XYZ2sRGB = [3.2404542, -1.5371385, -0.4985314;
           -0.9692660,  1.8760108,  0.0415560;
            0.0556434, -0.2040259,  1.0572252];
        
combinedM = Pro2XYZ' * D50_D65' * XYZ2sRGB';


% f = fopen('test.txt','r');
% for i = 1:498
imList = dir('input/TIF/480p_16bits_Pro_WB');
imList = {imList(3:end).name};
for i = 1:numel(imList)
%     name = fgets(f);
%     name = name(1:end-1);
    name = imList{i}(1:end-4);
    im = imread(fullfile('input/TIF/480p_16bits_Pro_WB',[name '.tif']));
    im = im2double(im);
    [h,w,~] = size(im);
    im = reshape(im,[w*h,3]);

    im_XYZ = im * Pro2XYZ';

    im_XYZ = reshape(im_XYZ,[h,w,3]);
    imwrite(im2uint16(im_XYZ),fullfile('input/PNG/480p_16bits_XYZ_WB',[name '.png']));
end
% fclose(f);

**Comment by zhenhuahu** [comment]
Thanks for the prompt reply! This is indeed helpful! Now I understand the whole data preparation process. Thanks again for the great work and help!

**Comment by Jian-danai** [comment]
Do you have the code for HDR+ dataset XYZ to sRGB?
