### ISSUE TITLE
cudaCheckError() failed : invalid device function

### ISSUE THREAD

**Issue by yippp** [HuiZeng/Image-Adaptive-3DLUT#17]
PyTorch: 1.6, CUDA: 10.0
According to the README, modified the code, and also modified the `setup.sh` to`export CUDA_HOME=/usr/local/cuda-10.0`.
But when I try to run `demo_eval.py`, I meet the error:

> `cudaCheckError() failed : invalid device function`
> `Process finished with exit code 139`

Does anyone knows how to solve that? I have no idea after search on Google.

**Comment by lld533** [comment]
> PyTorch: 1.6, CUDA: 10.0
> According to the README, modified the code, and also modified the `setup.sh` to`export CUDA_HOME=/usr/local/cuda-10.0`.
> But when I try to run `demo_eval.py`, I meet the error:
> 
> > `cudaCheckError() failed : invalid device function`
> > `Process finished with exit code 139`
> 
> Does anyone knows how to solve that? I have no idea after search on Google.

If you install pytorch 1.6 via conda or pip, please check the corresponding CUDA version. In my view, the precompiled pytorch 1.6 wheel is compatible with CUDA 10.1 and 10.2, instead of 10.0. Could you please upgrade your CUDA to version 10.2 (along with your nvidia driver to version 430 or later)? FYI, we tested the code on a machine with Ubuntu 18.04 + Python 3.6 + PyTorch 1.6 + CUDA 10.2 + nvidia driver 440.100.

**Comment by yippp** [comment]
> > PyTorch: 1.6, CUDA: 10.0
> > According to the README, modified the code, and also modified the `setup.sh` to`export CUDA_HOME=/usr/local/cuda-10.0`.
> > But when I try to run `demo_eval.py`, I meet the error:
> > > `cudaCheckError() failed : invalid device function`
> > > `Process finished with exit code 139`
> > 
> > 
> > Does anyone knows how to solve that? I have no idea after search on Google.
> 
> If you install pytorch 1.6 via conda or pip, please check the corresponding CUDA version. In my view, the precompiled pytorch 1.6 wheel is compatible with CUDA 10.1 and 10.2, instead of 10.0. Could you please upgrade your CUDA to version 10.2 (along with your nvidia driver to version 430 or later)? FYI, we tested the code on a machine with Ubuntu 18.04 + Python 3.6 + PyTorch 1.6 + CUDA 10.2 + nvidia driver 440.100.

Thanks for your suggestion. I tried it on a machine with CUDA 10.2. It can work well.
