### ISSUE TITLE
Image Gradient in TrilinearBackward is not well calculated

### ISSUE THREAD

**Issue by bigeagle** [HuiZeng/Image-Adaptive-3DLUT#18]
Hi there,

In `TrilinearBackwardCpu`, I saw only `lut_grad` is well calculated, and `image_grad` is considered as identity.

In this artical, the gradient of image also needs to be backward passed to the CNN weight generation layers. A more correct graident calculation can make this project more elegant. 

Yours,

**Comment by HuiZeng** [comment]
Hi, the CNN weights are updated via the MSE loss. where gradient will be automatically backward.
The gradient of trilinear interpolation on input image does not affect the CNN model.

**Comment by bigeagle** [comment]
I see, you are correct. :)
