### ISSUE TITLE
Pretrained Model only provide three LUTs?

### ISSUE THREAD

**Issue by szhang67** [HuiZeng/Image-Adaptive-3DLUT#21]
I downloaded the pretrained model to test and found that it only provides access to first three LUTs. In the eval code, it is indicated that a full test should use 5 LUTs. I wonder if other pretrained LUTs will be released for me to test the performance of your work to a complete extent?

Thanks!

**Comment by HuiZeng** [comment]
what do you mean by "other pretrained LUTs"? Only three LUTs and a CNN model for one setting in our experiments.

**Comment by szhang67** [comment]
> what do you mean by "other pretrained LUTs"? Only three LUTs and a CNN model for one setting in our experiments.

Sorry, it was a misunderstanding. I saw in the code "demo_eval.py" that there are commented "#LUT3" and "#LUT4" and assumed maybe a total of five LUTs should be a complete test. (or does this suggest to try more LUTs? :)

**Comment by HuiZeng** [comment]
There is an ablation study on the number of LUTs in the paper.
In my experiments, three LUTs were enough to achieve SOTA performance. You may use more LUTs for more complex task.
