### ISSUE TITLE
train_input.txt和train_label.txt的来源

### ISSUE THREAD

**Issue by liangfeng-shuzhi** [HuiZeng/Image-Adaptive-3DLUT#22]
train_input.txt和train_label.txt中，图像列表是随机划分的吗？

为什么要分成input和label呀，有不同的作用吗？

**Comment by HuiZeng** [comment]
这个主要是针对unpaired训练划分的，这两个文件都是从deep photo enhancer拷贝过来的。

**Comment by liangfeng-shuzhi** [comment]
感谢解答~

**Comment by xuhui1994** [comment]
> 这个主要是针对unpaired训练划分的，这两个文件都是从deep photo enhancer拷贝过来的。
作者你好，那我使用的image_adaptive_lut_train_paired.py的时候，看字面意思是paired，默认的数据集也是train_input.txt和train_label.txt，但是您刚刚回答是针对unpaired训练划分的，这算冲突了吗？还有使用image_adaptive_lut_train_unpaired.py时，使用的数据集和image_adaptive_lut_train_paired.py是一致的吗?还是要修改，期待您的回答
