### ISSUE TITLE
unpaired中的img2 的作用是什么

### ISSUE THREAD

**Issue by xuhui1994** [HuiZeng/Image-Adaptive-3DLUT#25]
**return {"A_input": img_input, "A_exptC": img_exptC, "B_exptC": img2, "input_name": img_name}**
作者，我想了解再unpaired形式的训练中的img2 的作用是什么， 我看到在fiveK和hdrplus数据集中都用到了这个参数，一直没想明白，望解答，thank you very much

**Comment by HuiZeng** [comment]
这个只在unpaired训练的时候有用，unpaired训练时候用img2作为target。参考unpaired训练代码的第210行使用了这个数据。

**Comment by xuhui1994** [comment]
真的很感谢你，现在差不多都懂了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiZeng/Image-Adaptive-3DLUT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 下午3:45
收件人:&nbsp;"HuiZeng/Image-Adaptive-3DLUT"<Image-Adaptive-3DLUT@noreply.github.com&gt;;
抄送:&nbsp;"威爵"<978188311@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HuiZeng/Image-Adaptive-3DLUT] unpaired中的img2 的作用是什么 (#25)





 
这个只在unpaired训练的时候有用，unpaired训练时候用img2作为target。参考unpaired训练代码的第210行使用了这个数据。

**Comment by sunyclj** [comment]
> 这个只在unpaired训练的时候有用，unpaired训练时候用img2作为target。参考unpaired训练代码的第210行使用了这个数据。

请问非图像对的训练怎么理解呢，input和target不是同一场景，这样模型拟合不会有色彩差异吗？
