### ISSUE TITLE
'ImportError: libc10.so: cannot open shared object file' after build cpp

### ISSUE THREAD

**Issue by tnt-ooo-tnt** [HuiZeng/Image-Adaptive-3DLUT#28]
Sorry, I am a newbie for this part

I am having a difficulty with building the package 'trilinear'

I have followed the guide in README but it doesn't work with the message 'ImportError: libc10.so: cannot open shared object file'

Do you have any idea of this phenomenon?

I am using following environment

Python 3.7.6
torch==1.7.0
torchvision==0.8.1
numpy==1.19.4
opencv-python==4.4.0

nvcc v10.0
GPU: Tesla K80

Any comments are welcomed .. Thank you

**Comment by lld533** [comment]
> Sorry, I am a newbie for this part
> 
> I am having a difficulty with building the package 'trilinear'
> 
> I have followed the guide in README but it doesn't work with the message 'ImportError: libc10.so: cannot open shared object file'
> 
> Do you have any idea of this phenomenon?
> 
> I am using following environment
> 
> Python 3.7.6
> torch==1.7.0
> torchvision==0.8.1
> numpy==1.19.4
> opencv-python==4.4.0
> 
> nvcc v10.0
> GPU: Tesla K80
> 
> Any comments are welcomed .. Thank you

Make sure pytorch is imported before your compiled trilinear package in python3.7.
# Import in this way
import torch
import trilinear

# A bad example
import trilinear
# I believe this will cause ImportError: libc10.so
import torch

If this happens to solve your problem, the error is caused by the fact that any 3rd party package (including trilinear) depends on pytorch core libraries (including lic10.so). Thus, you have to import necessary pytorch libraries before any 3rd party packages.

BTW, we haven't checked if our code is compatible with pytorch 1.7 and CUDA 11.0.

**Comment by tnt-ooo-tnt** [comment]
> > Sorry, I am a newbie for this part
> > I am having a difficulty with building the package 'trilinear'
> > I have followed the guide in README but it doesn't work with the message 'ImportError: libc10.so: cannot open shared object file'
> > Do you have any idea of this phenomenon?
> > I am using following environment
> > Python 3.7.6
> > torch==1.7.0
> > torchvision==0.8.1
> > numpy==1.19.4
> > opencv-python==4.4.0
> > nvcc v10.0
> > GPU: Tesla K80
> > Any comments are welcomed .. Thank you
> 
> Make sure pytorch is imported before your compiled trilinear package in python3.7.
> 
> ## Import in this way
> import torch
> import trilinear
> 
> ## A bad example ( I believe this will cause ImportError: libc10.so)
> import trilinear
> import torch
> 
> If this happens to solve your problem, the error is caused by the fact that any 3rd party package (including trilinear) depends on pytorch core libraries (including lic10.so). Thus, you have to import necessary pytorch libraries before any 3rd party packages.
> 
> BTW, we haven't checked if our code is compatible with pytorch 1.7 and CUDA 11.0.

Thanks a lot :) !!!!!!!!!!

**Comment by maralzar** [comment]
same issue but I import first torch and then trilinear but I have also this bug.
