### ISSUE TITLE
Dataset download failed

### ISSUE THREAD

**Issue by yitian8377** [HuiZeng/Image-Adaptive-3DLUT#32]
Thank you for your efforts. Under the link of the dataset, the download dataset is incomplete or the download fails. I want to confirm whether the dataset path has changed? Could you please attach a link to Baidu Cloud? Thank you very much!

**Comment by HuiZeng** [comment]
Hi，thanks for pointing out this issue. 
Unfortunately, my Baidu Cloud account does not have enough space to upload the entire dataset.

**Comment by HuiZeng** [comment]
Hi, I have uploaded the datasets to Baidu Cloud.
