### ISSUE TITLE
How do you keep the white balance after the 3DLUT operation

### ISSUE THREAD

**Issue by YolandaZhu** [HuiZeng/Image-Adaptive-3DLUT#33]
For example, lut[33][33][33] ={0.8224368, 0.82099277, 0.8277654}.
The color of colorless issues will be changed after the 3DLUT operation。
The diagonal r:g: b of the cube should be 1:1:1

**Comment by HuiZeng** [comment]
Hi, we do not intentionally keep the white balance. 
Actually, color enhancement will inevitably change white balance. White balance can also be learned using our model.
