### ISSUE TITLE
你好，运行的时候遇到两个问题，希望可以得到您的回复

### ISSUE THREAD

**Issue by meihao5631** [HuiZeng/Image-Adaptive-3DLUT#34]
您好，运行image_adaptive_lut_evaluation.py代码的时候，环境是按照你的要求配置的，但是报错RuntimeError: PyTorch was compiled without NumPy support，网上的解决方法不管用；
另外想问一下，这个代码支持多卡运行吗？
很感谢您分享的代码，期待回复哈~祝好~

**Comment by HuiZeng** [comment]
这个代码训练和测试都不怎么费GPU，单卡就能跑的很快。至于编译问题，这个每个人的环境都不一样，需要你自己多查一查了。

**Comment by meihao5631** [comment]
好的，谢谢你哈～------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Hui&amp;nbsp;Zeng&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月28日(星期六) 下午5:08
收件人:&nbsp;&quot;HuiZeng/Image-Adaptive-3DLUT&quot;<Image-Adaptive-3DLUT@noreply.github.com&gt;;
抄送:&nbsp;&quot;meihao5631&quot;<277173922@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HuiZeng/Image-Adaptive-3DLUT] 你好，运行的时候遇到两个问题，希望可以得到您的回复 (#34)
