### ISSUE TITLE
Visualization of LUTs

### ISSUE THREAD

**Issue by tnt-ooo-tnt** [HuiZeng/Image-Adaptive-3DLUT#35]
Hi, very honor to see your works

Actually I have trained with my custom dataset, but there are some issues I cannot verify with my knowledge.

So I am trying to analyze the shapes(?) of LUTs

Is there any tool to visualize the LUTs which can show the results just like in your paper?

Thank you for the answer

**Comment by HuiZeng** [comment]
Hi, sorry for the late reply.
I do have a matlab code to visualize the learned 3D LUTs. However, I am currently taking a quarantine and unavilable to this code.
I will update the code after the quarantine.

**Comment by tnt-ooo-tnt** [comment]
I am so afraid to hear that
I hope you get well soon, cheers 👍

**Comment by HuiZeng** [comment]
Hi， I have uploaded the code for visualization of learned luts. 

There are two steps:
1. run the python code to write the learned lut into a .txt file.
2. run the matlab code to visualize the 3d lut.

You may need to check the paths and file names according to your own enviroments.

**Comment by hkzhang95** [comment]
I am a little confused about the visualization results.

From my understanding, the visualization of 3D LUT should be a point cube in which each point matches a new color. Here is an example from the internet:

![LUT](https://www.displaycalibrations.com/images/slider/Cube_Resolution/3D_LUT_17-Point_Cube.png)

However, the visualization results from Fig.4 in the paper are not exact cubes. So I am wondering about the meanings of the axes in each figure. Maybe for each component (e.g. R), the visualization should be a cube, then each point (R_in, G_in, B_in) matches a new R-value?

**Comment by HuiZeng** [comment]
Hi， the example you provide is indeed more vivid.  In this 3D cube, each point contains three values, namely, the {R_out, G_out. B_out}, rather than one single value. It actually contains 4D information. Unfortunately, I do not know how to plot 3D LUT like this. Also it is inconvenient to see the details in such a dense plot. 

Instead, I choose to visualize the R, G, B channel independently. Your understanding is right. The three axes represent the R_in, G_in, B_in while the output R (or G, or B) values are plotted as multiple slices rather than one cube. You can also choose to visualize all R values as a cube if you like.

**Comment by tnt-ooo-tnt** [comment]
Thank you for your effort a lot,

I will let this issue be opened for a several days if you don't mind for derived discussion.

Thank you again so much

**Comment by hkzhang95** [comment]
> Hi， the example you provide is indeed more vivid. In this 3D cube, each point contains three values, namely, the {R_out, G_out. B_out}, rather than one single value. It actually contains 4D information. Unfortunately, I do not know how to plot 3D LUT like this. Also it is inconvenient to see the details in such a dense plot.
> 
> Instead, I choose to visualize the R, G, B channel independently. Your understanding is right. The three axes represent the R_in, G_in, B_in while the output R (or G, or B) values are plotted as multiple slices rather than one cube. You can also choose to visualize all R values as a cube if you like.

Maybe I did not make myself clear enough.

You said that `The three axes represent the R_in, G_in, B_in`. But from your [code](https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/visualization_lut/visualize_lut.m#L91), the third axis represents the value of R/G/B. So from my viewpoint, one of the axis information is missing, and this is the reason why the visualization result is not a standard cube.

**Comment by hkzhang95** [comment]
I will provide a python script to visualize the LUT like the example I provided if I am available. : ）

**Comment by HuiZeng** [comment]
> > Hi， the example you provide is indeed more vivid. In this 3D cube, each point contains three values, namely, the {R_out, G_out. B_out}, rather than one single value. It actually contains 4D information. Unfortunately, I do not know how to plot 3D LUT like this. Also it is inconvenient to see the details in such a dense plot.
> > Instead, I choose to visualize the R, G, B channel independently. Your understanding is right. The three axes represent the R_in, G_in, B_in while the output R (or G, or B) values are plotted as multiple slices rather than one cube. You can also choose to visualize all R values as a cube if you like.
> 
> Maybe I did not make myself clear enough.
> 
> You said that `The three axes represent the R_in, G_in, B_in`. But from your [code](https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/visualization_lut/visualize_lut.m#L91), the third axis represents the value of R/G/B. So from my viewpoint, one of the axis information is missing, and this is the reason why the visualization result is not a standard cube.

Yes, you are right. I just checked the code. It actually plots (R_in, G_in, R_out/G_out/B_out) and there are a total of six dimensions (R_in, G_in, B_in, R_out, G_out, B_out). 
That will be great if you can provide a more elegent visualization script.

**Comment by hkzhang95** [comment]
Hi, I write a simple python script for visualization at #37. Please have a check about whether it is correct.

**Comment by HuiZeng** [comment]
> Hi, I write a simple python script for visualization at #37. Please have a check about whether it is correct.

Hi, many thanks for your help. I have merged your python script and also updated the matlab code.
It seems this issue can be closed.

**Comment by darkzbaron** [comment]
Can this be used in color grading software?
