### ISSUE TITLE
About detailed architecture of the CNN model

### ISSUE THREAD

**Issue by yitian8377** [HuiZeng/Image-Adaptive-3DLUT#36]
1）Given an input image of any resolution, you simply use bilinear interpolation to downsample it to 256 x 256。Why did you put this step in the network instead of image preprocessing? Is this equivalent?
2）If I don’t want to use InstanceNorm, are there any suggestions for modifying the architecture of the CNN model?
3）Since bilinear interpolation is time-consuming, will it affect the result if I change it to nearest neighbor?

Looking forward to your reply！

**Comment by HuiZeng** [comment]
Hi，
1) using bilinear in pytorch is just for convenience. Different implementations of interpolation may slightly affect the the performance. You can replace it with preprocessing or nearest neighbor. I guess there should be no obvious difference if you use the same implementation during training and evaluation stages.
2) instanceNorm is also not necessary for practical applications. You can replace the CNN model with any architecture you like. In some practical application, I actually find that using models pretrained on imagenet can obtain better performance.
