### ISSUE TITLE
Abnormal loss of D during training

### ISSUE THREAD

**Issue by 952640557** [HuiZeng/Image-Adaptive-3DLUT#38]
Hey, thanks for your great work!

I 've trained the model using the unpaired version of code and got great results. But I found the loss of D was quiet abnormal:  D always give the fake and real input very close scores（at least same signal), no matter how many epochs we train, even when the 800 epochs meet the  end and visualization of the result was quiet good. I wonder how could the result get that good with such a weak D and unbalance scores between G&D?

**Comment by HuiZeng** [comment]
Hi， thanks for your interest.
I am not an expert on GAN so I cannot answer your question :(
The unpaired settings are mainly following DPE and tuned empirically.

**Comment by 952640557** [comment]
I read the DPE paper after received your reply and I found this paper have proposed the 2-way A-WGAN with iBN, which is not used in your work. 

I wonder if it's because you tried and found that it didn't bring improvement？

**Comment by HuiZeng** [comment]
CycleGAN or the 2-way A-WGAN can be useful in some unpaired learning applications. However, I did not try such complicated  designs on the 3D LUT model since it is not the main focus of this work.
