### ISSUE TITLE
Question about quantitative comparison of photo retouching results

### ISSUE THREAD

**Issue by sangenan** [HuiZeng/Image-Adaptive-3DLUT#39]
I'm very interested in your work! But, When I read the paper, I found a problem why is the PSNR value of UPE much lower than that of HDRNet in your paper. As shown in the figure below:
![image](https://user-images.githubusercontent.com/8358472/103186739-add04c80-48fc-11eb-84cd-5d131df930b7.png)
However, The paper on Underexposed Photo Enhancement using Deep Illumination Estimation Indicates that their model performance is higher than HDRNet
![image](https://user-images.githubusercontent.com/8358472/103186994-a65d7300-48fd-11eb-94a9-7d3bb21572ec.png)

**Comment by HuiZeng** [comment]
Hi, you'd better ask this question to the authors of UPE. I asked for the training code from them but still cannot repreduce their results. For some reason, they did not release their training code up to now.

**Comment by HuiZeng** [comment]
Hi, you'd better ask this question to the authors of UPE. I asked for the training code from the first author of UPE but still cannot repreduce their results. For some reason, they have not released their training code yet.

**Comment by sangenan** [comment]
Thank you for your reply~
