### ISSUE TITLE
ModuleNotFoundError: No module named 'trilinear._ext'; 'trilinear' is not a package

### ISSUE THREAD

**Issue by ShirleyYim** [HuiZeng/Image-Adaptive-3DLUT#4]
envs: trilinear_cpp. pytorch 1.6

**Comment by HuiZeng** [comment]
Hi, the python wrapper of trilinear_cpp needs to be modified. This will be supported in a few days.

**Comment by GuideWsp** [comment]
I have sucessfully test it on FiveK dataset on pytorch-1.5.1, you can found solution in https://github.com/HuiZeng/Image-Adaptive-3DLUT/issues/5
