### ISSUE TITLE
FiveK的DNG图像是如何转换成JPG图像的？

### ISSUE THREAD

**Issue by redleay** [HuiZeng/Image-Adaptive-3DLUT#43]
您好，请问FiveK数据集中的DNG图像，是如何转换成JPG图像的？使用了什么软件，需要设置什么参数，这些的信息可以提供一下吗？感谢~

**Comment by cxzhou95** [comment]
@redleay 你好，我也有同样的疑问，请问你搞清楚了吗，谢谢！
