### ISSUE TITLE
something wrong with unpaired pretrained model 

### ISSUE THREAD

**Issue by KevenLee** [HuiZeng/Image-Adaptive-3DLUT#46]
Is the unpaired pretrained model mismatched ?

RuntimeError: Error(s) in loading state_dict for Classifier:
        Missing key(s) in state_dict: "model.7.weight", "model.7.bias", "model.9.weight", "model.9.bias", "model.13.weight", "model.13.bias", "model.16.weight", "model.16.bias".
        Unexpected key(s) in state_dict: "model.8.weight", "model.8.bias".
        size mismatch for model.6.weight: copying a param with shape torch.Size([64, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for model.6.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for model.10.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
        size mismatch for model.12.weight: copying a param with shape torch.Size([3, 128, 8, 8]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for model.12.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([128]).

**Comment by uidser** [comment]
How did it work out?

**Comment by uidser** [comment]
怎么解决的？我也遇到这个问题了
