### ISSUE TITLE
About wlsTonemap

### ISSUE THREAD

**Issue by YinengXiong** [HuiZeng/Image-Adaptive-3DLUT#47]
Hi, the provided local tone mapping code is written in MATLAB
`
%% Finally, shift, scale, and gamma correct the result
gamma = 1.0/1.0;
bias = -min(OUT(:));
gain = 0.8;
OUT = (gain*(OUT + bias)).^gamma;
% figure
imshow(OUT);
imwrite(OUT,'a1509_T.jpg');
`
I found that the range of OUT is not in [0, 1], when I convert this script to Python, the result is not correct when using min-max normalization, do you know how to normalize it in python?

**Comment by HuiZeng** [comment]
Hi, you may try directly clamp the output to the range [0,1].

**Comment by YinengXiong** [comment]
Thank you very much
