### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by z1076820548** [HuiZeng/Image-Adaptive-3DLUT#48]
作者你好！我想问一下你运行项目所使用的cuda版本，使用 python3 image_adaptive_lut_evaluation.py后，总是出现问题，我想可能是环境导致的，，望回复，感谢！问题如下：
/root/anaconda3/envs/pytorch041_2/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/root/anaconda3/envs/pytorch041_2/lib/python3.6/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument

**Comment by luckhui0505** [comment]
解决了吗？我也有这样问题
