### ISSUE TITLE
Error occurred when I replace the image in sRGB

### ISSUE THREAD

**Issue by BeyondHeaven** [HuiZeng/Image-Adaptive-3DLUT#49]
Hi,
I tested it successfully with the original image(a duck eating grass).
But when I replace it with another jpg image, an error occurred: 

> Traceback (most recent call last):
  File "demo_eval.py", line 86, in <module>
    LUT = generate_LUT(img)
  File "demo_eval.py", line 66, in generate_LUT
    pred = classifier(img).squeeze()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dockerdata/ruodai1/Image-Adaptive-3DLUT/models_x.py", line 99, in forward
    return self.model(img_input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 4, 256, 256] to have 3 channels, but got 4 channels instead

I use the snipper in windows to get this image and save it in jpg format. Is there anything wrong? Thanks!

**Comment by BeyondHeaven** [comment]
Image must be resized to (1080, 1620)

**Comment by zhanghongyong123456** [comment]
> Hi, I tested it successfully with the original image(a duck eating grass). But when I replace it with another jpg image, an error occurred:
> 
> > Traceback (most recent call last):
> > File "demo_eval.py", line 86, in 
> > LUT = generate_LUT(img)
> > File "demo_eval.py", line 66, in generate_LUT
> > pred = classifier(img).squeeze()
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/dockerdata/ruodai1/Image-Adaptive-3DLUT/models_x.py", line 99, in forward
> > return self.model(img_input)
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
> > input = module(input)
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward
> > return self._conv_forward(input, self.weight)
> > File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
> > self.padding, self.dilation, self.groups)
> > RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 4, 256, 256] to have 3 channels, but got 4 channels instead
> 
> I use the snipper in windows to get this image and save it in jpg format. Is there anything wrong? Thanks!

windows  setup trilinear_cpp error 
![image](https://user-images.githubusercontent.com/48466610/157632543-39d457b1-fd6a-4141-a359-b08fcb104929.png)
