### ISSUE TITLE
There is some bug on trilinear_cpp version.

### ISSUE THREAD

**Issue by GuideWsp** [HuiZeng/Image-Adaptive-3DLUT#5]
Pytorch version: 1.5.1, cuda: 9.0
Error follows:  AttributeError: module 'trilinear_cpp.trilinear' has no attribute 'trilinear_forward_cuda'

So you have to modify
https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/trilinear_cpp/src/trilinear_cuda.cpp#L32
to 
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("trilinear_forward_cuda", &trilinear_forward_cuda, "Trilinear forward");
  m.def("trilinear_backward_cuda", &trilinear_backward_cuda, "Trilinear backward");
}

Finally, I can run it on the demo_images, the results is very good.

**Comment by ShirleyYim** [comment]
I build the trilinear_cpp module sucessfully. but how to import the trilinear module in the model.py??

**Comment by GuideWsp** [comment]
> I build the trilinear_cpp module sucessfully. but how to import the trilinear module in the model.py??

you can modify it as dcn https://github.com/xinntao/EDVR/tree/master/basicsr/models/ops/dcn

**Comment by HuiZeng** [comment]
> Pytorch version: 1.5.1, cuda: 9.0
> Error follows: AttributeError: module 'trilinear_cpp.trilinear' has no attribute 'trilinear_forward_cuda'
> 
> So you have to modify
> https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/trilinear_cpp/src/trilinear_cuda.cpp#L32
> to
> PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
> m.def("trilinear_forward_cuda", &trilinear_forward_cuda, "Trilinear forward");
> m.def("trilinear_backward_cuda", &trilinear_backward_cuda, "Trilinear backward");
> }
> 
> Finally, I can run it on the demo_images, the results is very good.

Hi, this is a clever way to make it work on the demo code. There may still be some problems for training.
I am currently working on an urgent project. I will update to pytorch 1.x and double-check training and evaluation details in a few days.

**Comment by JuZiSYJ** [comment]
> > I build the trilinear_cpp module sucessfully. but how to import the trilinear module in the model.py??
> 
> you can modify it as dcn https://github.com/xinntao/EDVR/tree/master/basicsr/models/ops/dcn

hello, could please tell more details in **model.py**,thanks!  By the way, the CUDA version in my machine is **CUDA10.2**, is there any problems that will occur in the running time?

**Comment by GuideWsp** [comment]
Will you provide more about the error?

**Comment by JuZiSYJ** [comment]
> Will you provide more about the error?

thanks, i build it successfully in pytroch **1.1**, CUDA10.2, **But** when i try the demo, it occurs     f
rom trilinear._ext import trilinear
ModuleNotFoundError: No module named 'trilinear._ext'; 'trilinear' is not a packag

so i also try it in pytorch **0.4.1**, CUDA 10.2, build it successfully, But when i run the demo, it ouucues
    from ._trilinear import lib as _lib, ffi as _ffi
ImportError: /home/syj/pycharm/code/lowlevel/Image-Adaptive-3DLUT-master/trilinear/_ext/trilinear/_trilinear.so: undefined symbol: __cudaRegisterFatBinaryEnd

i search it, it seems it is must be complied in **CUDA9.0**?

**Comment by GuideWsp** [comment]
1. you should new "__init__.py" and "trilinear_func.py"
2. you should put "TrilinearInterpolation" into "trilinear_func"
3. you import it  as "from trilinear_cpp import TrilinearInterpolation"

**Comment by JuZiSYJ** [comment]
> 1. you should new "**init**.py" and "trilinear_func.py"
> 2. you should put "TrilinearInterpolation" into "trilinear_func"
> 3. you import it  as "from trilinear_cpp import TrilinearInterpolation"

thanks a lot, i run the demo successfully under pytroch 1.1, CUDA10.2
1.make some change in  https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/trilinear_cpp/src/trilinear_cuda.cpp#L32 

2.sh ./setup.sh,   notice clear the thing built before

3.do as **GuideWsp** said, in **trilinear_func.py**  
'''python
 import trilinear
class TrilinearInterpolation(torch.autograd.Function):
'''

**Comment by HuiZeng** [comment]
I have uploaded the python wrapper to support pytorch 1.x. 
The python code needs to be slightly changed. Details can be found in the readme.

**Comment by UtopiaHu** [comment]
Can the code run on Windows enviroment?

**Comment by HuiZeng** [comment]
> Can the code run on Windows enviroment?

We have not tested it on Windows.

**Comment by suolaka** [comment]
> > 1. you should new "**init**.py" and "trilinear_func.py"
> > 2. you should put "TrilinearInterpolation" into "trilinear_func"
> > 3. you import it  as "from trilinear_cpp import TrilinearInterpolation"
> 
> thanks a lot, i run the demo successfully under pytroch 1.1, CUDA10.2
> 1.make some change in https://github.com/HuiZeng/Image-Adaptive-3DLUT/blob/master/trilinear_cpp/src/trilinear_cuda.cpp#L32
> 
> 2.sh ./setup.sh, notice clear the thing built before
> 
> 3.do as **GuideWsp** said, in **trilinear_func.py**
> '''python
> import trilinear
> class TrilinearInterpolation(torch.autograd.Function):
> '''

Hello, I've had this problem too. I want to ask you how to write this **trilinear_func.py** Can you send the contents of  **trilinear_func.py**?
