### ISSUE TITLE
高分辨率图片（6000x4000）效果如何改进

### ISSUE THREAD

**Issue by zener90818** [HuiZeng/Image-Adaptive-3DLUT#50]
您好，我想处理高分辨率的图片6000x4000，想请教下，加大3Dlut的维度（比如256），或者采用更大的分类骨干网络能否提高效果呢，您能提供一些建议吗，非常感谢
我用您的网络训练了自己的数据，长宽进行了5倍下采样，PSNR能达到33左右，如果原图输入，能否通过上述改动进一步提高效果呢？

**Comment by HuiZeng** [comment]
我暂时没有试过提升输入分辨率对效果的影响，因为输入分辨率提升会极大的提升网络部分的计算量。
根据实际任务的复杂度，可以尝试更复杂的网络结构和更多的LUT数量，比如我在项目中用过resnet34作为特征提取网络，同时将LUT数量增加到30个，在我所做的任务上性能提升也很大，提升LUT维度对改善一些badcase，尤其是断层问题也比较明显，对PSNR的提升好像不是特别大，我最多用过64维，256维一个3D LUT的参数量就会非常大了。
如果不计计算和存储代价的话，LUT维度，模型深度，LUT数量提升都可以增加整体表达能力。

**Comment by zener90818** [comment]
好的，非常感谢

**Comment by zener90818** [comment]
好的，非常感谢

**Comment by zener90818** [comment]
好的，非常感谢
