### ISSUE TITLE
关于batch size问题

### ISSUE THREAD

**Issue by zener90818** [HuiZeng/Image-Adaptive-3DLUT#52]
您好，我将代码改成单卡多batchsize进行训练，psnr值反而没有batchsize为1时效果好，请问这个是什么原因导致的呢，如果是多GPU训练，每张GPU上batchsize为1，最终效果是否也没有单卡单batchsize效果好呢，

**Comment by HuiZeng** [comment]
我在FiveK上的实验结果确实是batchsize=1最好，具体原因我也不太情况。多卡的情况没有测试过。

**Comment by zener90818** [comment]
好的，非常感谢。

**Comment by ironheads** [comment]
> 您好，我将代码改成单卡多batchsize进行训练，psnr值反而没有batchsize为1时效果好，请问这个是什么原因导致的呢，如果是多GPU训练，每张GPU上batchsize为1，最终效果是否也没有单卡单batchsize效果好呢，

或许这个可以解释[issue](https://github.com/HuiZeng/Image-Adaptive-3DLUT/issues/72#issuecomment-1245295278)
