### ISSUE TITLE
关于多阶段任务问题

### ISSUE THREAD

**Issue by zener90818** [HuiZeng/Image-Adaptive-3DLUT#54]
您好，麻烦请教下，我现在想做图像增强任务：一张图片要经过色温调整，对比度调整，颜色调整三种递进的流程，要输出三张不同调整效果图，我想在您的网络结构下将这三个处理过程串行在一起，分阶段进行监督（LUT有三组），我这边有的数据对是一张图片对应三张效果图，这样的流程可行吗，有没有考虑用ssim，lpips来进行监督呢，效果怎么样呢？我这边有A,B,C,D四中数据，是由A->B->C->D依次调整生成的，我用了您的网络直接A->B, A->C, A->D，训练的结果PSNR值从高到底依次下降的，如果是上面这套流程A为输入，用B,C,D进行监督不知道是否可行呢？

**Comment by HuiZeng** [comment]
你这里分步骤是必须的吗？如果不必须，3D LUT是可以把这些事情一起做了，即直接从A-->D。
如果必须拆分开的话，训练起来可能会有些麻烦，每一步的输出都需要截断到[0,1]，拆成多步训练的最终效果好像也如一步到位的好。我只试过两阶段，暂时还没有特别成功的经验。

**Comment by zener90818** [comment]
是的，需要生成中间调整过的图片。好的，非常感谢。
