### ISSUE TITLE
Question about install trilinear module

### ISSUE THREAD

**Issue by PedestrianZQZ** [HuiZeng/Image-Adaptive-3DLUT#56]
Hi, thanks for your outstanding work!

when I try to setup the environment following the readme, I found the trilinear module can't be built correctly.

The output of `sh setup.sh` is
`Including CUDA code.
'nvalid command name 'install
`

and when I run `python3 image_adaptive_lut_train_unpaired.py`, the output is 
`Traceback (most recent call last):
  File "image_adaptive_lut_train_unpaired.py", line 18, in <module>
    from models_x import *
  File "/mnt/home/zyc/TransITM/test/Image-Adaptive-3DLUT/models_x.py", line 9, in <module>
    import trilinear
ModuleNotFoundError: No module named 'trilinear'`

Can you help me with that? thanks a lot

**Comment by djdll** [comment]
您好，虽然我不是作者但是我也遇到了您的问题，刚好看到可以给你一个我的解决方法，linux下需要确定两件事，第一个是cuda11需要修改export TORCH_CUDA_ARCH_LIST="8.0" ，还有就是gcc和g++版本要确定不能太低我是6.0。希望可以帮到你

**Comment by PedestrianZQZ** [comment]
> 您好，虽然我不是作者但是我也遇到了您的问题，刚好看到可以给你一个我的解决方法，linux下需要确定两件事，第一个是cuda11需要修改export TORCH_CUDA_ARCH_LIST="8.0" ，还有就是gcc和g++版本要确定不能太低我是6.0。希望可以帮到你

谢谢您

**Comment by cailijing** [comment]
> 您好，虽然我不是作者但是我也遇到了您的问题，刚好看到可以给你一个我的解决方法，linux下需要确定两件事，第一个是cuda11需要修改export TORCH_CUDA_ARCH_LIST="8.0" ，还有就是gcc和g++版本要确定不能太低我是6.0。希望可以帮到你

您好，请问export TORCH_CUDA_ARCH_LIST="8.0"要在哪儿添加和运行啊
