### ISSUE TITLE
Eval images corrupt when training using unpaired dataset

### ISSUE THREAD

**Issue by youyuge34** [HuiZeng/Image-Adaptive-3DLUT#67]
When I try to train on my own dataset using unpaired way, the GAN loss became abnormal and the eval image is corrupted.
I have tried training unpaired data from scratch or finetune by loading your weights of .pth, but the results are both just like below. Is it due to the instability of GAN？

```
[Epoch 21/800] [Batch 800/3000] [D: -22.295015, G: 183.243387] [pixel: 0.016258] [tv: 0.002546, wnorm: 3.558231, mn: 0.016558] ETA: 14 days, 4:21:33.761969
```

![2B0114000000x6palEBFD_Q100 jpg](https://user-images.githubusercontent.com/15784256/182984413-d0871bac-3349-4c07-a9aa-cd9a522ef7cc.jpg)

**Comment by HuiZeng** [comment]
The unpaired setting is usually quite unstable and the parameters are sensitive to different datasets. You may try to use larger constraints on the 3D LUT to improve the stability of the learning process then finetune these parameters to get balance between performance and stability.
