### ISSUE TITLE
Could you please release the code of "local tone mapping + 3D LUT" ?

### ISSUE THREAD

**Issue by hermosayhl** [HuiZeng/Image-Adaptive-3DLUT#7]
I'm very interested in your work! Especially, how does it work when **local tone mapping** is applied. Looking forward!

**Comment by HuiZeng** [comment]
Hi , the local tone mapping code used in the paper is uploaded. 
It is matlab code borrowed from WLS tone mapping. I replace the WLS filter with guided filter.
There are several parameters in such kind of methods. It is a little bit trivial to tune these parameters.

For high-dynamic range images, I first applied local tone mapping to it and saved the images. Then the saved images are fed into the LUT to get the final results.

**Comment by hermosayhl** [comment]
Thanks for your reply! It's a good job actually!
