### ISSUE TITLE
关于论文接受的问题/ about admission state of this work?

### ISSUE THREAD

**Issue by homurajiang** [HuiZeng/Image-Adaptive-3DLUT#8]
您好，请问您的这篇文章已经被TPAMI2020接受了吗？因为对论文内容很感兴趣，所以有点好奇工作是否被接受，谢谢您的解答！
Hello, If this work is admit by TPAMI 2020? I'm very interested in this paper,  thanks for you reply!

**Comment by HuiZeng** [comment]
是的，已经接收了。

**Comment by homurajiang** [comment]
非常棒的工作，感谢您的解答！
